name: E2E Tests

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  setup:
    name: e2e test setup
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.20.10'
          check-latest: true
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.15"
      - name: NPM Clean Install
        run: npm ci
        working-directory: ./contracts
      - name: Hardhat Clean
        run: npx hardhat clean
        working-directory: ./contracts
      - name: Hardhat Compile
        run: npx hardhat compile
        working-directory: ./contracts
      - name: Install AvalancheGo Release
        shell: bash
        run: BASEDIR=/tmp/e2e-test AVALANCHEGO_BUILD_PATH=/tmp/e2e-test/avalanchego ./scripts/install_avalanchego_release.sh
      - name: Build Subnet-EVM Plugin Binary
        shell: bash
        run: ./scripts/build.sh /tmp/e2e-test/avalanchego/plugins/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy

  precompile:
    name: Precompile Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run E2E Precompile Tests
        shell: bash
        run: AVALANCHEGO_BUILD_PATH=/tmp/e2e-test/avalanchego DATA_DIR=/tmp/e2e-test/precompile-data ./scripts/run_ginkgo_precompile.sh
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: subnet-evm-e2e-logs-precompile
          path: /tmp/network-runner-root-data*/
          retention-days: 5

  warp:
    name: Warp Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Warp E2E Tests
        shell: bash
        run: AVALANCHEGO_BUILD_PATH=/tmp/e2e-test/avalanchego DATA_DIR=/tmp/e2e-test/warp-data ./scripts/run_ginkgo_warp.sh
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: subnet-evm-e2e-logs-warp
          path: /tmp/network-runner-root-data*/
          retention-days: 5

  load:
    name: Load Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run E2E Load Tests
        shell: bash
        run: AVALANCHEGO_BUILD_PATH=/tmp/e2e-test/avalanchego DATA_DIR=/tmp/e2e-test/load-data ./scripts/run_ginkgo_load.sh
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: subnet-evm-e2e-logs-load
          path: /tmp/network-runner-root-data*/
          retention-days: 5
